CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name VARCHAR (255) UNIQUE NOT NULL,
    password VARCHAR (225) NOT NULL
);

CREATE TABLE music (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    song_name VARCHAR(255),
    group_one_two_beat_one VARCHAR (255),
    group_one_two_beat_two VARCHAR (255),
    group_two_one_beat_one VARCHAR (255),
    group_two_one_beat_two VARCHAR (255),
    group_two_one_beat_three VARCHAR (255),
    group_two_one_beat_four VARCHAR (255),
    group_three_two_beat_one VARCHAR (255),
    group_three_two_beat_two VARCHAR (255),
    sharable INTEGER DEFAULT 1 NOT NULL, 
    date_last_edited TIMESTAMP DEFAULT now() NOT NULL
);
